#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

module Qup
  module Adapter
    module Kestrel
      module Thrift
      end
    end
  end
end
